In [2]:
import numpy as np


In [3]:
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(phi, rho)

In [6]:
def identifier(img):
    k = 8;
#     IN2, R1-R7, D2-D8, 6 Hu Moments
    identifier = np.zeros(1,2*k+6);
    img_shape = shape(img)
    img_inv = np.ones(img_shape) - img
    pad_size = 3
    
#     Top
    if(sum(img_inv[0,:])==0):
        add = np.ones((pad_size,img_shape[1]))
        img = np.concatenate((add,img))
    elif(sum(img_inv[img_shape[0]-1,:])==0) :#Bottom
        add = np.ones((pad_size,img_shape[1]))
        img = np.concatenate((img, add))
        
    elif(sum(img_inv[:,1])==0) :#left
        add = np.ones((img_shape[0], pad_size))
        img = np.hstack(( add, img))
    
    elif(sum(img_inv[:,1])==0) :#right
        add = np.ones((img_shape[0], pad_size))
        img = np.hstack(( img, add))
    
    #Recalculte Centroid
    img_inv = np.ones(img_shape) - img
    
    N = img.shape[0]*img.shape[1]
    x,y = np.where(img == 0)
    
    
    #Find centroid 
    #gib code kinshuk
    
#     Find central moment of inertia
    I = sum(np.zqueeze((x - cent_x)**2 + (y - cent_y)**2));
    IN2 = I / N**2;
    identifier[0,0] = IN2
    
    x = img_shape[0]
    y = img_shape[1]
    
    dr = max(max(x - cent_x, cent_x), max(y - cent_y, cent_y))/(k+1)
    c,r = np.meshgrid(np.arange(x),np.arange(y))
    c = c + 1
    r = r + 1
    circvec = []
    
    coding = {}
    
    for i in range(1,k+1):
        rad = dr*i
        
        C = (((c - cent_x)**2 + (r - cent_y)**2)**0.5<=rad)^(((c - cent_x)**2 + (r - cent_y)**2)**0.5<=(rad-1))
        
        indx,indy = np.nonzero(C)
        indx = indx + 1
        indy = indy + 1
        cidx = (indx-1)*C.shape[0] + indy
        
        vals = []
        cx = c[indx-1,indy-1] - cent_x
        cy = r[indx-1,indy-1] - cent_y
        for m in range(len(cidx)):
            vals.append([cidx[m], cy[m], cx[m],0 ])
        print(vals)
        TH,_ = (cart2pol(vals[:,1], vals[:,2]))
        print(TH)
        vals[:,3] = TH

        print(vals)

        sortedvals =  vals[np.argsort(vals[:, 3])]
        print(sortedvals)
        circvec = img[np.unravel_index(soltedvals[:0], img.shape, 'F')]
        kernel = np.ones((2,1))
        circvec = cv2.morphologyEx(circvec, cv2.MORPH_OPEN, kernel)
        
        coding[i] = circvec
        
        if(len(circvec)!=0):
            
            
        

In [8]:
k = 8
x = 10
y = 15
cent_x = 5
cent_y = 5
c,r = np.meshgrid(np.arange(x),np.arange(y))
c = c + 1
r = r + 1
circvec = []

for i in range(1):
    rad = 3

    C = (((c - cent_x)**2 + (r - cent_y)**2)**0.5<=rad)^(((c - cent_x)**2 + (r - cent_y)**2)**0.5<=(rad-1))

    indx,indy = np.nonzero(C)
    indx = indx + 1
    indy = indy + 1
    cidx = (indx-1)*C.shape[0] + indy

    vals = []
    cx = c[indx-1,indy-1] - cent_x
    cy = r[indx-1,indy-1] - cent_y
    for m in range(cidx.shape[0]):
        vals.append([cidx[m], cy[m], cx[m],0 ])
    vals = np.array(vals, dtype = float)
    TH,_ = (cart2pol(vals[:,1], vals[:,2]))
    print(TH)
    vals[:,3] = TH
    
    print(vals)
    
    sortedvals =  vals[np.argsort(vals[:, 3])]
    print(sortedvals)
    circvec = img[np.unravel_index(soltedvals[:0]), img.shape, 'F')]

[ 3.14159265 -2.35619449 -2.67794504  2.67794504  2.35619449 -2.03444394
  2.03444394 -1.57079633  1.57079633 -1.10714872  1.10714872 -0.78539816
 -0.46364761  0.46364761  0.78539816  0.        ]
[[ 20.          -3.           0.           3.14159265]
 [ 33.          -2.          -2.          -2.35619449]
 [ 34.          -2.          -1.          -2.67794504]
 [ 36.          -2.           1.           2.67794504]
 [ 37.          -2.           2.           2.35619449]
 [ 48.          -1.          -2.          -2.03444394]
 [ 52.          -1.           2.           2.03444394]
 [ 62.           0.          -3.          -1.57079633]
 [ 68.           0.           3.           1.57079633]
 [ 78.           1.          -2.          -1.10714872]
 [ 82.           1.           2.           1.10714872]
 [ 93.           2.          -2.          -0.78539816]
 [ 94.           2.          -1.          -0.46364761]
 [ 96.           2.           1.           0.46364761]
 [ 97.           2.           2.  

char_inv = ones(size(char)) - char;

% If white border on any edge, pad with more 1s
pad = 3;
% top
if(sum(char_inv(1,:)) == 0)
    char = [ones(pad,size(char,2)) ;char];
end
% bottom
if(sum(char_inv(end,:)) == 0)
    char = [char; ones(pad,size(char,2))];
end
% left
if(sum(char_inv(:,1)) == 0)
    char = [ones(size(char,1),pad) char];
end
% right
if(sum(char_inv(:,end)) == 0)
    char = [char ones(size(char,1),pad)];
end
% Recalculate for centroid
char_inv = ones(size(char)) - char;

% figure, imshow(char,[]);
% title("char");
% figure, imshow(char_inv,[]);
% title("char_inv");

% Total number of pixels in character
N = sum(~char(:));
% Find x,y positions of 0 elements (character)
[y, x] = find(~char);

% Find centroid
cent = regionprops(char_inv,'centroid');
cent = cat(1, cent.Centroid);
cent_x = cent(1);
cent_y = cent(2);

% Find central moment of inertia
I = sum((x - cent_x).^2 + (y - cent_y).^2);
IN2 = I / N^2;
identifier(1) = IN2;
if(printIdent)
   fprintf('Normalized Central Moment: %.4f\n', IN2); 
end

% Extract Circular Topology Template and Diameter Ratio
y = size(char,1);
x = size(char,2);
dr = max(max(x - cent_x,cent_x), max(y - cent_y,cent_y)) / (k+1);
[c, r] = meshgrid(1:x, 1:y);

% Display Extracted circles
if(showFigs)
    figure(1);
    % Create copy of character to display circles overlaid
    tempcirc = char;
end

% Init coding vector for storing extra information
coding(k).circVec=[];
for i = 1:k
    rad = dr * i;
    % Create circle line of logical 1s to extract template
    C = xor(sqrt((c-cent_x).^2+(r-cent_y).^2)<=rad, ...
        sqrt((c-cent_x).^2+(r-cent_y).^2)<=(rad-1));
    % Extract circular template linear indices (sort based on theta)
    cidx = find(C);
    % Create matrix linear indices, corresponding x and y values
    vals = [cidx c(cidx)-cent_x r(cidx)-cent_y zeros(size(cidx,1),1)];
    % Add corresponding theta values
    [TH, ~] = cart2pol(vals(:,2), vals(:,3));
    vals(:,4) = TH;
    % Sort based on theta values so in order around circle
    [~, order] = sort(vals(:,4));
    sortedvals = vals(order,:);
    % Use linear indices to extract desired values in correct theta order
    circVec = char(sortedvals(:,1));
    
    % Show circles overlaid on character
    if(showFigs)
        tempcirc(C) = .5;
    end
    
    % Extract values from character based on circular indices. Start at
    %   0deg going CCW.
    circVec = imopen(circVec,ones(2,1));
    
    % Save vector for debugging or future use
    coding(i).circ = circVec;
    
    % If character is so small nothing is extracted, leave ident as 0
    if(~isempty(circVec))
        % Count number of sections of at least 2 0s. This is the number of
        % character sections the circle goes through.
        cnt = strfind([1 1 circVec'],[0 0]);
        coding(i).count = length(cnt(diff([1 cnt])~=1));

        % Save count to identifier vector
        identifier(1+i) = coding(i).count;
        if(showFigs)
            subplot(2,4,i);
            imshow(coding(i).circ);
            str = sprintf('%d',coding(i).count);
            title(str);
        end

        % Find 2 longest arcs of background and divide diff by total length
        % If 1s (background) wrap around, move all 1s to one side.
        circ = length(circVec);
        if(circVec(1) == 1 && circVec(end) == 1)
            idx = find(circVec==0,1,'last');
            circVec = [circVec(idx+1:end); circVec(1:idx)];
        end
        % Vector of length of each section of 1s
        B = [0 circVec' 0]; % Pad with 0s for diff
        bgrd_len = find(diff(B)==-1) - find(diff(B)==1);
        % If no crossings, set ratio to 0
        if(coding(i).count < 1);
            d2 = 0;
            d1 = 0;
        else
            % Get two longest sections (arcs)
            [d2, idx_d2] = max(bgrd_len);
            bgrd_len(idx_d2)=NaN;
            d1 = max(bgrd_len);
        end
        % Find ratio of difference of two longest arcs by circumference
        coding(i).ratio = (d2-d1) / circ;
        if(i > 1) % Only keep k-1 largest ratios
            if(~isnan(coding(i).ratio))
                identifier(k+i) = coding(i).ratio;
            end
        end
        if(printIdent)
            fprintf('Count=%d, d2=%d, d1=%d, c=%d, ratio = %.4f\n',...
                coding(i).count,d2,d1,circ,coding(i).ratio);
        end
    end
end

% Add Hu Moments to end of Identifier (work on inverse so char is 0)
eta_mat = SI_Moment(char_inv) ;
hu_arr = Hu_Moments(eta_mat);
% 1st moment is IN2, above, in first slot
identifier(2*k+1:end) = hu_arr(2:end);

% Show character with circles overlaid
if(showFigs)
    figure(2);
    imshow(tempcirc);
end


In [1]:
import matlab.engine

ModuleNotFoundError: No module named 'matlab.engine'; 'matlab' is not a package